# Generated by Django 4.1 on 2022-08-24 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project_Maintenance', '0001_initial'),
        ('User_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRatesHeader',
            fields=[
                ('ContractID', models.AutoField(primary_key=True, serialize=False)),
                ('SubContractor', models.CharField(max_length=512)),
                ('RatesAgreedBy', models.CharField(max_length=512)),
                ('LastModifiedOn', models.DateTimeField(auto_now=True)),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Maintenance.projectmaintenance')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RateUnit',
            fields=[
                ('RateUnitID', models.AutoField(primary_key=True, serialize=False)),
                ('UnitName', models.CharField(max_length=512)),
                ('UnitValue', models.CharField(max_length=512)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContractRateTransmit',
            fields=[
                ('TransmitID', models.AutoField(primary_key=True, serialize=False)),
                ('EmailtoSent', models.CharField(max_length=64)),
                ('LastModifiedOn', models.DateTimeField(auto_now=True)),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contract_Rates.contractratesheader')),
                ('SentByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_UserMaintenance', to='User_maintenance.usermaintenance')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContractRatesDetails',
            fields=[
                ('ContractDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('CodeID', models.CharField(max_length=512)),
                ('Rates', models.CharField(max_length=512)),
                ('LastModifiedOn', models.DateTimeField(auto_now=True)),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contract_Rates.contractratesheader')),
                ('RateUnitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contract_Rates.rateunit')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
