# Generated by Django 4.1 on 2022-08-24 17:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliesCodeMaintenance',
            fields=[
                ('supplies_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('sc_desc', models.CharField(max_length=100)),
                ('sc_billing_code', models.CharField(max_length=20)),
                ('sc_default_rates', models.IntegerField()),
                ('sc_active', models.BooleanField(default=1)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
