# Generated by Django 4.1 on 2022-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaintenance',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_number', models.IntegerField()),
                ('project_name', models.CharField(max_length=1024)),
                ('project_location', models.CharField(max_length=2056)),
                ('project_duration', models.IntegerField()),
                ('project_manager', models.CharField(max_length=1024)),
                ('last_modified_on', models.DateField()),
            ],
        ),
    ]
