# Generated by Django 4.1 on 2022-08-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
                ('RoleDescription', models.CharField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaintenance',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=1024)),
                ('LastName', models.CharField(max_length=1024)),
                ('PrimaryNumber', models.CharField(max_length=10)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('UserPassword', models.CharField(max_length=1024)),
                ('Company', models.CharField(max_length=1024)),
                ('Active', models.BooleanField(default=1)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('UserRoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_maintenance.userrole')),
            ],
        ),
    ]
