# Generated by Django 4.1 on 2022-08-24 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project_Maintenance', '0001_initial'),
        ('User_maintenance', '0001_initial'),
        ('labor_code_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCardSubmission',
            fields=[
                ('time_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('work_desc', models.CharField(max_length=100)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_maintenance.usermaintenance')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Maintenance.projectmaintenance')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeCardStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('rejection_reason', models.CharField(max_length=100)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_maintenance.usermaintenance')),
                ('time_card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_card_approval.timecardsubmission')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeCardDetails',
            fields=[
                ('time_card_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(choices=[('Manager', 'Manager'), ('Labor', 'Labor')], default='Labor', max_length=10)),
                ('person_who_worked', models.CharField(max_length=100)),
                ('small_tools', models.BooleanField(default=False)),
                ('per_diem', models.BooleanField(default=False)),
                ('ppe', models.BooleanField(default=False)),
                ('prp', models.BooleanField(default=False)),
                ('pfp', models.BooleanField(default=False)),
                ('vehicle', models.CharField(choices=[('Trailer', 'Trailer'), ('Pickup Truck', 'Pickup Truck')], default='Trailer', max_length=20)),
                ('mileage', models.IntegerField()),
                ('hotel_code', models.CharField(choices=[('Actual Cost', 'Actual Cost'), ('Flat Rate', 'Flat Rate')], max_length=20)),
                ('hotel_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_time', models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (25, '25 minutes'), (30, '30 minutes'), (35, '35 minutes'), (40, '40 minutes'), (45, '45 minutes'), (60, '1 hour'), (120, '2 hour'), (180, '3 hour'), (240, '4 hour'), (300, '5 hour'), (360, '6 hour'), (420, '7 hour'), (480, '8 hour')], default=5)),
                ('total_hour', models.IntegerField(editable=False)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_code_maintenance.laborcodemaintenance')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_maintenance.usermaintenance')),
                ('time_card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_card_approval.timecardsubmission')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
